# build environment
FROM node:alpine as builder

COPY header /header

WORKDIR /app

COPY angular/package.json .
COPY angular/package-lock.json .

RUN npm install

COPY angular .

RUN npm run build

# production environment
FROM nginx:alpine

COPY nginx-app.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist/angular /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
